name: job_intelligence
version: '1.0.0'
config-version: 2

profile: 'job_intelligence'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  job_intelligence:
    staging:
      +materialized: view
      +schema: staging
    processing:
      +materialized: table
      +schema: processing
    marts:
      +materialized: table
      +schema: marts

vars:
  # Default variables
  max_job_age_days: 90
  embedding_model: 'e5-base-v2'
