-- User-facing tables and views
USE DATABASE JOB_INTELLIGENCE;
USE ROLE ACCOUNTADMIN;

-- Create application role
CREATE ROLE IF NOT EXISTS JOB_APP_ROLE;
GRANT ROLE JOB_APP_ROLE TO ROLE SYSADMIN;

-- Grant read access to application role
GRANT USAGE ON DATABASE JOB_INTELLIGENCE TO ROLE JOB_APP_ROLE;
GRANT USAGE ON SCHEMA MARTS TO ROLE JOB_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS TO ROLE JOB_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE JOB_APP_ROLE;

-- Create user-specific tables
USE SCHEMA MARTS;

-- Saved jobs table
CREATE TABLE IF NOT EXISTS USER_SAVED_JOBS (
    user_id VARCHAR(100),
    job_id VARCHAR(255),
    source VARCHAR(50),
    saved_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    notes TEXT,
    PRIMARY KEY (user_id, job_id, source)
) COMMENT = 'User saved jobs';

-- Job applications tracking
CREATE TABLE IF NOT EXISTS USER_APPLICATIONS (
    application_id VARCHAR(100) DEFAULT UUID_STRING() PRIMARY KEY,
    user_id VARCHAR(100),
    job_id VARCHAR(255),
    source VARCHAR(50),
    application_date DATE,
    status VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'User job applications tracking';

-- User resumes table
CREATE TABLE IF NOT EXISTS USER_RESUMES (
    resume_id VARCHAR(100) DEFAULT UUID_STRING() PRIMARY KEY,
    user_id VARCHAR(100),
    resume_text TEXT,
    resume_embedding VECTOR(FLOAT, 768),
    skills TEXT,
    uploaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'User uploaded resumes';

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_SAVED_JOBS TO ROLE JOB_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_APPLICATIONS TO ROLE JOB_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_RESUMES TO ROLE JOB_APP_ROLE;
